[2025-04-22T22:08:26.208+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T22:08:26.217+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: law_enforcement_ELT_dbtcloud.trigger_dbt_job manual__2025-04-22T22:08:25.182134+00:00 [queued]>
[2025-04-22T22:08:26.221+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: law_enforcement_ELT_dbtcloud.trigger_dbt_job manual__2025-04-22T22:08:25.182134+00:00 [queued]>
[2025-04-22T22:08:26.221+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-22T22:08:26.231+0000] {taskinstance.py:2888} INFO - Executing <Task(DbtCloudRunJobOperator): trigger_dbt_job> on 2025-04-22 22:08:25.182134+00:00
[2025-04-22T22:08:26.237+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'law_enforcement_ELT_dbtcloud', 'trigger_dbt_job', 'manual__2025-04-22T22:08:25.182134+00:00', '--job-id', '569', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/Lab2_ELT.py', '--cfg-path', '/tmp/tmpwch_jrz1']
[2025-04-22T22:08:26.239+0000] {standard_task_runner.py:105} INFO - Job 569: Subtask trigger_dbt_job
[2025-04-22T22:08:26.239+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1229) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-22T22:08:26.239+0000] {standard_task_runner.py:72} INFO - Started process 1230 to run task
[2025-04-22T22:08:26.266+0000] {task_command.py:467} INFO - Running <TaskInstance: law_enforcement_ELT_dbtcloud.trigger_dbt_job manual__2025-04-22T22:08:25.182134+00:00 [running]> on host 3fa5927efcb0
[2025-04-22T22:08:26.340+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='law_enforcement_ELT_dbtcloud' AIRFLOW_CTX_TASK_ID='trigger_dbt_job' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T22:08:25.182134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T22:08:25.182134+00:00'
[2025-04-22T22:08:26.342+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-22T22:08:26.366+0000] {connection.py:277} WARNING - Connection schemes (type: dbt_cloud) shall not contain '_' according to RFC3986.
[2025-04-22T22:08:26.368+0000] {base.py:84} INFO - Retrieving connection 'dbt_cloud'
[2025-04-22T22:08:26.374+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/dbt/cloud/operators/dbt.py", line 187, in execute
    trigger_job_response = self.hook.trigger_job_run(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/dbt/cloud/hooks/dbt.py", line 68, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/dbt/cloud/hooks/dbt.py", line 603, in trigger_job_run
    return self._run_and_get_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/dbt/cloud/hooks/dbt.py", line 342, in _run_and_get_response
    return self.run(endpoint=full_endpoint, data=payload, extra_options=extra_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 189, in run
    prepped_request = session.prepare_request(req)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 444, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'https:///xs917.us1.dbt.com/api/v2/accounts/70471823454988/jobs/70471823455826/run/': No host supplied
[2025-04-22T22:08:26.413+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=law_enforcement_ELT_dbtcloud, task_id=trigger_dbt_job, run_id=manual__2025-04-22T22:08:25.182134+00:00, execution_date=20250422T220825, start_date=20250422T220826, end_date=20250422T220826
[2025-04-22T22:08:26.422+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-22T22:08:26.423+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 569 for task trigger_dbt_job (Invalid URL 'https:///xs917.us1.dbt.com/api/v2/accounts/70471823454988/jobs/70471823455826/run/': No host supplied; 1230)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/dbt/cloud/operators/dbt.py", line 187, in execute
    trigger_job_response = self.hook.trigger_job_run(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/dbt/cloud/hooks/dbt.py", line 68, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/dbt/cloud/hooks/dbt.py", line 603, in trigger_job_run
    return self._run_and_get_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/dbt/cloud/hooks/dbt.py", line 342, in _run_and_get_response
    return self.run(endpoint=full_endpoint, data=payload, extra_options=extra_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 189, in run
    prepped_request = session.prepare_request(req)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 444, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'https:///xs917.us1.dbt.com/api/v2/accounts/70471823454988/jobs/70471823455826/run/': No host supplied
[2025-04-22T22:08:26.467+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-22T22:08:26.475+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T22:08:26.476+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
